# fly.toml app configuration file generated for p4 on 2024-12-12T20:44:26+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "p4"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/movies?page=1"

[env]
  API_URL = "https://p4.fly.dev"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
